// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPbiAskQy7GLB0bHZUYu56093XXdTC2O0',
    appId: '1:78677696376:web:26c54603886c33b28eb28d',
    messagingSenderId: '78677696376',
    projectId: 'ditch-perfect-26',
    authDomain: 'ditch-perfect-26.firebaseapp.com',
    storageBucket: 'ditch-perfect-26.firebasestorage.app',
    measurementId: 'G-SY10RZCFNW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn8Xi9oH2C__bpXgwkRzBOjkY6p6fycko',
    appId: '1:78677696376:android:613ee8f07c84aee58eb28d',
    messagingSenderId: '78677696376',
    projectId: 'ditch-perfect-26',
    storageBucket: 'ditch-perfect-26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAH3xZTIL06zGODxuntlXhIXXYMYbIJ6FM',
    appId: '1:78677696376:ios:fd5219470521eccd8eb28d',
    messagingSenderId: '78677696376',
    projectId: 'ditch-perfect-26',
    storageBucket: 'ditch-perfect-26.firebasestorage.app',
    iosBundleId: 'com.example.flutterTestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAH3xZTIL06zGODxuntlXhIXXYMYbIJ6FM',
    appId: '1:78677696376:ios:fd5219470521eccd8eb28d',
    messagingSenderId: '78677696376',
    projectId: 'ditch-perfect-26',
    storageBucket: 'ditch-perfect-26.firebasestorage.app',
    iosBundleId: 'com.example.flutterTestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPbiAskQy7GLB0bHZUYu56093XXdTC2O0',
    appId: '1:78677696376:web:a8657e46d25209ad8eb28d',
    messagingSenderId: '78677696376',
    projectId: 'ditch-perfect-26',
    authDomain: 'ditch-perfect-26.firebaseapp.com',
    storageBucket: 'ditch-perfect-26.firebasestorage.app',
    measurementId: 'G-7MR9M0HKGJ',
  );
}
